version: "3.7"
services:
  db:
    image: mysql:5.7
    platform: linux/amd64 
    restart: always
    container_name: algorithm-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=algorithm
      - MYSQL_ROOT_PASSWORD=algorithm
      - TZ=Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - ./data:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
